services:
  db:
    container_name: mysql_db_tp
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "test"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
